### PR TITLE
Upgraded hamamatsu camera classes to allow multiple cameras

### PR DESCRIPTION
**Pull request by jeffmoffitt**
We made a few minor changes to Hamamatsu classes to configure these cameras so that one (or more) can be triggered from another.

### CODE REVIEW

**Comment by HazenBabcock** [comment]
Hm, I'm not sure about this one. 
* Why are you eliminating the "output_trigger_polarity[0]" parameter?
* There is no need to record 'is_master' since you are using it in the same method.
* Why do you set camera parameters to hard coded values in captureSetup? Don't these just override the users requested values for these parameters?

**Comment by HazenBabcock** [comment]
Sorry, regarding the 3rd point, I see now that you added this to the __init__() method. Still not sure it is a good idea to do it this way.

**Comment by jeffmoffitt** [comment]
We are certainly happy to revise in anyway you see fit.

A few comments on your points:

   - Why are you eliminating the "output_trigger_polarity[0]" parameter?

Honestly, this was a holdover from a larger change we were thinking about
implementing. The idea was that there are some camera properties that the
user probably should not be able to access. Happy to roll this change back.

   - There is no need to record 'is_master' since you are using it in the
   same method.

Agreed. We were following the style of the Andor camera classes. Again,
happy to roll this back if you like.

   - Why do you set camera parameters to hard coded values in captureSetup?
   Don't these just override the users requested values for these parameters?

These changes followed a debate as to whether it was better to have the
cameras completely configured in the config.xml file or whether there were
some properties that we basically going to be always the same, in which
case, it might be 'safer' to simply have the hamamatsu class make them the
standard.

Do you have a preference?

**Comment by HazenBabcock** [comment]
On further reflection, in my opinion the right way to do this is to have camera properties specified in the XML for the camera. This would deal with several issues, such as not all cameras from the same manufacturer necessarily have all the same properties. In the XML you could also specify the initial values for the properties you are interested in and whether they are modifiable. I agree this is not as 'safe' as hard coding (and it would also probably break all existing config.xml files) but I think the benefit of the ability to more easily support more cameras outweighs the risk.

Anyway, that is probably too much work for now, so please keep `output_trigger_polarity[0]`. I assume it is there because someone needed it, and I'd prefer not to just yank it away. Maybe @emanuega has some additional thoughts?

Looking at the Andor camera class use of `is_master`... Not sure this is optimal either... I'm not sure why the user would want to change `Exposure_Time` for a slave camera, but I'm also not sure why we'd want to deny them that ability. Or maybe this is an Andor quirk? Externally timed cameras can't control their exposure time? I leave it up to you whether your want use `is_master` or `self.is_master`.

**Comment by HazenBabcock** [comment]
I just checked the history for `hamamatsuCameraControl.py`, looks like @leonardosepulveda  wanted that for some reason.

**Comment by jeffmoffitt** [comment]
I have incorporated these comments into a different version and different pull request. I am closing this request.

**Pull request closed without merging**
