### PR TITLE
Added some installation examples using Conda

### PR DESCRIPTION
**Pull request by leonardosepulveda**
I thought this could be useful info for neophytes like me. I tested the commands an all of them work.

### CODE REVIEW

**Comment by leonardosepulveda** [comment]
A mistake. I used "--name myenv" in all cases. I checked again and it works.

**Comment by HazenBabcock** [comment]
Do you mean "it works" as described in this pull request and we should merge it? Or "it works" with `--name myenv`? If the latter please fix the pull request.

**Comment by leonardosepulveda** [comment]
Sorry for the confusion. The installation works when following the instructions in the fixed pull request.

**Comment by HazenBabcock** [comment]
Okay, thanks!

**Pull request merged**
